### ISSUE TITLE
Constituency results: Fix mobile navigation

### ISSUE THREAD

**Issue by simonplend** [voteforpolicies/data-website#2]
Once you've tapped on a constituency to view results you can no longer get back to the list of constituencies.

URL: https://data.voteforpolicies.org.uk/constituencies/results

**Comment by ryanhyslop** [comment]
Could try and take a look at this, thinking the tab navigation here isn't quite appropriate.

Not sure what you think Simon but that constituency list is massive, could toy with adding a search/filtering input that on selecting the constituency it loads the results beneath.

Since we're not really leveraging a framework that might give us some of these quick wins, I've had a quick look at http://www.listjs.com/ and created a quick prototype:

![screen shot 2015-04-01 at 22 54 31](https://cloud.githubusercontent.com/assets/323687/6953570/1ad8a8a6-d8c2-11e4-9138-2e14b6b93580.png)
![screen shot 2015-04-01 at 22 53 59](https://cloud.githubusercontent.com/assets/323687/6953571/1adbe124-d8c2-11e4-8179-c7d5c779d11c.png)

Thoughts?

**Comment by simonplend** [comment]
@ryanhyslop That looks fantastic - I'm all for it! Would neatly resolve this issue as well: https://github.com/voteforpolicies/data-website/issues/10.

**Comment by simonplend** [comment]
@ryanhyslop Worth keeping an eye on this as it will have an impact on how this search feature works: https://github.com/voteforpolicies/data-website/issues/9 - hopefully it will be merged in before you implement this search feature.

**Comment by EddyLane** [comment]
@ryanhyslop I've updated the map for performance and now I'd like to add in a similar search feature to what you've got here but I don't want to duplicate any work. Have you got the mark-up/code you've used on this prototype available anywhere? /cc @simonplend

**Comment by ryanhyslop** [comment]
Apologies for the delay, the bank holiday wasn't as kind to my free time ( or liver ) as I'd hoped!

The prototype was mainly to demonstrate the idea so theres nothing to share as such, but since theres an obvious case for reuse I'll try and consider making it as modular as I can, or at least get it up here to review.

I've spent a little bit of time this evening on this and will hopefully have something in the next couple of days.

**Comment by simonplend** [comment]
@ryanhyslop No problem. Looking forward to seeing what you come up with! Just shout on Slack if there's anything you'd like to discuss.

**Comment by simonplend** [comment]
Resolved. Thanks, @ryanhyslop! :smile_cat:
