### ISSUE TITLE
Test coverage/NPM/Bower

### ISSUE THREAD

**Issue by EddyLane** [voteforpolicies/data-website#22]
Hi,

I'd like to start a **discussion** about test coverage and package management for this project.

Currently we don't have any tests but as we push the project forward for the GE, and indeed past the election (I believe the main site can be easily updated for the subsequent GE), I think getting some test coverage onto the data site would benefit us all.

Personally I advocate adding unit tests with [karma](http://karma-runner.github.io/) to the project and leaving it at this for now (forgoing integration/acceptance/whatever tests for now)

These are the pros/cons as I personally see them:

Benefits:

* Less bugs as development continues
* Easier to refactor code
* Forces more modular/re-usable code
* Serves as documentation

Cons:

* Higher barrier to entry

Some questions if we were to go this way:

* Which framework to use? The biggest two are Jasmine and Mocha.

This does lead me to my next question about our dependency management. 

At the moment we're committing our deps direct to this repository but I feel this isn't maintainable as more  deps are added and we want to update to different versions. I was wondering how people feel about introducing [NPM](https://www.npmjs.com/) and/or [Bower](http://bower.io/) as package managements for our project?

These are the pros/cons as I personally see them:

Pros:

* Less convoluted repo
* Easier to update libraries
* Easier to test (**npm test** for example)

Cons:

* Bit more tricky for Windows developers

So to surmise:

1. Do you feel like we should introduce unit tests to this repo?
2. Do you feel like we should introduce package management to the project?

Lets get a dialog going about these :)

**Comment by ryanhyslop** [comment]
My brief 2 cents:

1. Given the relatively high barrier to entry with tests, and the idea that this, or at least should be, a 'web page' primarily and not an application of sorts, I'd possibly say that its not a priority. Which is a shame as generally yea its a good idea, organising and enforcing it somehow would be a bit of a burden. Karma and Mocha for me if that was the direction we headed though.

2. Absolutely, we've got some serious questions around our tooling at the moment, I appreciate keeping the barrier to entry low but theres a massive benefit to having an opinionated set of tools that can guide contribution, ideally we shouldn't be committing any vendor or compiled code to the repo. I'll let @simonplend weigh in here though before I go too far :)

**Comment by simonplend** [comment]
My thoughts on this:

1. I agree with Ryan's point on this. Tests would be ideal, but they don't feel like a priority at the moment. If and when we do implement tests, I'm on board with Karma and Mocha.

2. Yep. I suggest we add Browserify - that will allow us to create proper modules as well as use npm for vendor dependencies. What do you think? If you're happy with that, I can put the basics in place, but I'll need your help with modularising everything.

On a more general note, I think you're spot on @ryanhyslop when you say that "there's a massive benefit to having an opinionated set of tools that can guide contribution". The priority so far for the data site has been getting something up and running with an unfortunately limited amount of spare time, but now is clearly the time to get things in decent shape so that this codebase is a pleasure to work with :+1:

**Comment by simonplend** [comment]
I've discussed this on Slack and we're agreed on getting Browserify in place. New issue for that here: https://github.com/voteforpolicies/data-website/issues/31

@EddyLane @ryanhyslop Happy for me to close this issue?

**Comment by simonplend** [comment]
Closing this issue to keep things tidy, but happy to reopen it if there are any objections!
