### ISSUE TITLE
Set up Browserify and refactor JavaScript into CommonJS modules

### ISSUE THREAD

**Issue by simonplend** [voteforpolicies/data-website#31]
See this discussion for the background to this: https://github.com/voteforpolicies/data-website/issues/22

**Comment by EddyLane** [comment]
Will have a go at this next couple of evenings

**Comment by ryanhyslop** [comment]
Just a heads up here that since we've going for Docpad it does come with a browserify plugin, which does just seem like adding some 'meta' to the top of the js files:
https://github.com/docpad/docpad-plugin-browserifydocs

Not quite as nice as having a gulp file configuration, but benefit of keeping everything within docpad, no idea how successful integrating it will be without trying though.

**Comment by simonplend** [comment]
I've not used any Browserify plugins for DocPad before, but I'm not sure that putting config for Browserify in the document meta is a particularly tidy solution - just a gut feeling, not that I've seen it in action of course (what I've put in the current DocPad PR for including scripts is just a temporary solution).

From my limited experience with Browserify, creating `npm` task for compiling JS with Browserify for production and development works really well. watchify makes it pretty easy to create an `npm` task that is suitable for development. I'm not a big fan of task runners like Grunt (which I've used quite a bit in the past) or Gulp as I feel they introduce a lot of complexity and unnecessary dependencies. These posts neatly sum up my feelings on 'em (disclaimer: written by a friend):

- http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/
- http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

Just my two cents, anyway, open to other ideas.
